### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by Speedy1991** [pretix/pretix-docker-compose#1]
Hi!
I try to run Pretix via docker-compose and if i get it running i will open a PR if you are interested.
The current state is:
- compose is starting without errors
- database doesn't get migrated
- website isn't reachable

I hope you can help me figure out the problems.
The isn't any error to see except  `pretix_1  | 2017-09-13 19:14:04,988 INFO exited: pretixtask (exit status 1; not expected)`

Here are my files + config + docker output

docker-compose.yml:
```
version: '2'
services:
  db:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=pretix
      - MYSQL_USER=pretix
      - MYSQL_PASSWORD=pretix
      - MYSQL_RANDOM_ROOT_PASSWORD=1

  redis:
    image: redis:latest

  pretix:
    image: pretix/standalone
    volumes:
      - pretix-data:/data
      - ./etc:/etc/pretix/
    ports:
      - "0.0.0.0:8345:8345"
    depends_on:
      - db
      - redis
      
  
volumes:
  pretix-data:

```

pretix.cfg:
```

[pretix]
instance_name=My pretix installation
url=localhost
currency=EUR
; DO NOT change the following value, it has to be set to the location of the
; directory *inside* the docker container
datadir=/data

[database]
; Replace mysql with postgresql_psycopg2 for PostgreSQL
backend=mysql
name=pretix
user=pretix
password=pretix
; Replace with host IP address for PostgreSQL
host=db

[mail]
; See config file documentation for more options
from=tickets@yourdomain.com
; This is the default IP address of your docker host in docker's virtual
; network. Make sure postfix listens on this address.
host=172.17.0.1

[redis]
location=redis?db=0
; Remove the following line if you are unsure about your redis' security
; to reduce impact if redis gets compromised.
sessions=true

[celery]
backend=redis+socket://redis?virtual_host=1
broker=redis+socket://redis?virtual_host=2
```

Full output of docker:
```
$ docker-compose up  --force-recreate --build
Recreating pretix_db_1 ...
Recreating pretix_db_1
Recreating pretix_redis_1 ...
Recreating pretix_redis_1 ... done
Recreating pretix_pretix_1 ...
Recreating pretix_pretix_1 ... done
Attaching to pretix_db_1, pretix_redis_1, pretix_pretix_1
redis_1   | 1:C 13 Sep 19:13:48.931 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1   | 1:C 13 Sep 19:13:48.931 # Redis version=4.0.1, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1   | 1:C 13 Sep 19:13:48.931 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
db_1      | 2017-09-13 19:13:49 139725978556288 [Note] mysqld (mysqld 10.2.7-MariaDB-10.2.7+maria~jessie) starting as process 1 ...
db_1      | 2017-09-13 19:13:49 139725978556288 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1      | 2017-09-13 19:13:49 139725978556288 [Note] InnoDB: Uses event mutexes
db_1      | 2017-09-13 19:13:49 139725978556288 [Note] InnoDB: Compressed tables use zlib 1.2.8
db_1      | 2017-09-13 19:13:49 139725978556288 [Note] InnoDB: Using Linux native AIO
db_1      | 2017-09-13 19:13:49 139725978556288 [Note] InnoDB: Number of pools: 1
db_1      | 2017-09-13 19:13:49 139725978556288 [Note] InnoDB: Using SSE2 crc32 instructions
db_1      | 2017-09-13 19:13:49 139725978556288 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
db_1      | 2017-09-13 19:13:49 139725978556288 [Note] InnoDB: Completed initialization of buffer pool
db_1      | 2017-09-13 19:13:49 139725240645376 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1      | 2017-09-13 19:13:49 139725978556288 [Note] InnoDB: Highest supported file format is Barracuda.
db_1      | 2017-09-13 19:13:49 139725978556288 [Note] InnoDB: 128 out of 128 rollback segments are active.
db_1      | 2017-09-13 19:13:49 139725978556288 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1      | 2017-09-13 19:13:49 139725978556288 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1      | 2017-09-13 19:13:49 139725978556288 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1      | 2017-09-13 19:13:49 139725978556288 [Note] InnoDB: Waiting for purge to start
db_1      | 2017-09-13 19:13:49 139725978556288 [Note] InnoDB: 5.7.18 started; log sequence number 10897290
db_1      | 2017-09-13 19:13:49 139725000136448 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1      | 2017-09-13 19:13:49 139725978556288 [Note] Plugin 'FEEDBACK' is disabled.
db_1      | 2017-09-13 19:13:49 139725978556288 [Note] Server socket created on IP: '::'.
db_1      | 2017-09-13 19:13:49 139725978556288 [Warning] 'proxies_priv' entry '@% root@9fc6669132a6' ignored in --skip-name-resolve mode.
db_1      | 2017-09-13 19:13:49 139725000136448 [Note] InnoDB: Buffer pool(s) load completed at 170913 19:13:49
pretix_1  | Operations to perform:
pretix_1  |   Apply all migrations: auth, banktransfer, contenttypes, easy_thumbnails, otp_static, otp_totp, paypal, pretixbase, pretixdroid, pretixmultidomain, sessions, stripe
pretix_1  | Running migrations:
pretix_1  |   No migrations to apply.
pretix_1  |   Your models have changes that are not yet reflected in a migration, and so won't be applied.
pretix_1  |   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
pretix_1  | 2017-09-13 19:13:51,529 CRIT Supervisor running as root (no user in config file)
pretix_1  | 2017-09-13 19:13:51,536 INFO RPC interface 'supervisor' initialized
pretix_1  | 2017-09-13 19:13:51,536 CRIT Server 'unix_http_server' running without any HTTP authentication checking
pretix_1  | 2017-09-13 19:13:51,536 INFO supervisord started with pid 11
pretix_1  | 2017-09-13 19:13:52,539 INFO spawned: 'pretixweb' with pid 14
pretix_1  | 2017-09-13 19:13:52,543 INFO spawned: 'pretixtask' with pid 15
pretix_1  | 2017-09-13 19:13:52,552 INFO spawned: 'nginx' with pid 16
pretix_1  | 2017-09-13 19:13:53,663 INFO success: pretixweb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
pretix_1  | 2017-09-13 19:13:53,664 INFO success: pretixtask entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
pretix_1  | 2017-09-13 19:13:53,664 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
pretix_1  | 2017-09-13 19:14:04,988 INFO exited: pretixtask (exit status 1; not expected)
pretix_1  | 2017-09-13 19:14:05,996 INFO spawned: 'pretixtask' with pid 67
pretix_1  | 2017-09-13 19:14:06,999 INFO success: pretixtask entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
pretix_1  | 2017-09-13 19:14:09,399 INFO exited: pretixtask (exit status 1; not expected)
pretix_1  | 2017-09-13 19:14:10,405 INFO spawned: 'pretixtask' with pid 79
pretix_1  | 2017-09-13 19:14:11,408 INFO success: pretixtask entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
pretix_1  | 2017-09-13 19:14:13,244 INFO exited: pretixtask (exit status 1; not expected)
Gracefully stopping... (press Ctrl+C again to force)
Stopping pretix_pretix_1 ...
Stopping pretix_redis_1 ...
Stopping pretix_db_1 ...
Killing pretix_pretix_1 ... done
Killing pretix_redis_1 ... done
Killing pretix_db_1 ... done
```

**Comment by DottoreTozzi** [comment]
I, too, am having problems getting this to run.

Log Output:
```
pretix         | 2019-04-08T20:57:31.080402957Z /usr/local/bin/python3: No module named pretix
pretix         | 2019-04-08T20:57:31.274181105Z 2019-04-08 20:57:31,273 CRIT Supervisor running as root (no user in config file)
pretix         | 2019-04-08T20:57:31.274221132Z 2019-04-08 20:57:31,274 WARN No file matches via include "/etc/supervisord-*.conf"
pretix         | 2019-04-08T20:57:31.281304612Z 2019-04-08 20:57:31,281 INFO RPC interface 'supervisor' initialized
pretix         | 2019-04-08T20:57:31.281317031Z 2019-04-08 20:57:31,281 CRIT Server 'unix_http_server' running without any HTTP authentication checking
pretix         | 2019-04-08T20:57:31.281459316Z 2019-04-08 20:57:31,281 INFO supervisord started with pid 8
pretix         | 2019-04-08T20:57:32.285216056Z 2019-04-08 20:57:32,284 INFO spawned: 'pretixweb' with pid 11
pretix         | 2019-04-08T20:57:32.288078155Z 2019-04-08 20:57:32,287 INFO spawned: 'pretixtask' with pid 12
pretix         | 2019-04-08T20:57:32.288908704Z 2019-04-08 20:57:32,288 INFO spawned: 'nginx' with pid 13
pretix         | 2019-04-08T20:57:32.549444950Z 2019-04-08 20:57:32,549 INFO exited: pretixweb (exit status 3; not expected)
pretix         | 2019-04-08T20:57:32.615621559Z 2019-04-08 20:57:32,615 INFO exited: pretixtask (exit status 1; not expected)
pretix         | 2019-04-08T20:57:33.619496394Z 2019-04-08 20:57:33,618 INFO spawned: 'pretixweb' with pid 25
pretix         | 2019-04-08T20:57:33.622238473Z 2019-04-08 20:57:33,621 INFO spawned: 'pretixtask' with pid 26
pretix         | 2019-04-08T20:57:33.622395557Z 2019-04-08 20:57:33,622 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
pretix         | 2019-04-08T20:57:33.830641885Z 2019-04-08 20:57:33,830 INFO exited: pretixweb (exit status 3; not expected)
pretix         | 2019-04-08T20:57:33.893761333Z 2019-04-08 20:57:33,893 INFO exited: pretixtask (exit status 1; not expected)
pretix         | 2019-04-08T20:57:35.898820365Z 2019-04-08 20:57:35,898 INFO spawned: 'pretixweb' with pid 37
pretix         | 2019-04-08T20:57:35.901282693Z 2019-04-08 20:57:35,900 INFO spawned: 'pretixtask' with pid 38
pretix         | 2019-04-08T20:57:36.126513091Z 2019-04-08 20:57:36,126 INFO exited: pretixweb (exit status 1; not expected)
pretix         | 2019-04-08T20:57:36.174755438Z 2019-04-08 20:57:36,174 INFO exited: pretixtask (exit status 1; not expected)
pretix         | 2019-04-08T20:57:39.181241544Z 2019-04-08 20:57:39,180 INFO spawned: 'pretixweb' with pid 50
pretix         | 2019-04-08T20:57:39.183880527Z 2019-04-08 20:57:39,183 INFO spawned: 'pretixtask' with pid 51
pretix         | 2019-04-08T20:57:39.392211525Z 2019-04-08 20:57:39,392 INFO exited: pretixweb (exit status 3; not expected)
pretix         | 2019-04-08T20:57:39.441469383Z 2019-04-08 20:57:39,441 INFO gave up: pretixweb entered FATAL state, too many start retries too quickly
pretix         | 2019-04-08T20:57:39.458095648Z 2019-04-08 20:57:39,457 INFO exited: pretixtask (exit status 1; not expected)
pretix         | 2019-04-08T20:57:40.459785951Z 2019-04-08 20:57:40,459 INFO gave up: pretixtask entered FATAL state, too many start retries too quickly
```

docker-compose.yml section:
```
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - default

  pretix:
    image: pretix/standalone:stable
    container_name: pretix
    hostname: tickets
    domainname: heimbrauconvention.de
    depends_on:
      - redis
    ports:
      - "8000:80"
    volumes:
      - ${DOCKERDIR}/pretix/config/pretix.cfg:/etc/pretix/pretix.cfg
#      - ${DOCKERDIR}/pretix/pretix-data:/data
      - pretix-data:/data
      - ${DOCKERDIR}/pretix/src:/pretix/src
    networks:
      - default
      - traefik_proxy
    labels:
      - "traefik.domain=heimbrauconvention.de"
      - "traefik.frontend.rule=Host:tickets.heimbrauconvention.de"
      - "traefik.port=80"
      - "traefik.enable=true"
      - "traefik.backend=pretix"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=heimbrauconvention.de"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=false"
```

docker-compose.yml volumes and networks section:
```
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

volumes:
  openpdata:
    driver: local
  maildata:
    driver: local
  mailstate:
    driver: local
  pretix-data:
    driver: local
```

pretix.cfg:
```
[pretix]
instance_name=HBCon Pretix
url=https://tickets.heimbrauconvention.de
currency=EUR
; DO NOT change the following value, it has to be set to the location of the
; directory *inside* the docker container
datadir=/data

[database]
; Replace postgresql with mysql for MySQL
backend=postgresql
name=pretix
user=pretix
; Replace with the password you chose above
password=xxxxxxxxxx
; In most docker setups, 172.17.0.1 is the address of the docker host. Adjuts
; this to wherever your database is running, e.g. the name of a linked container
; or of a mounted MySQL socket.
host=172.17.0.1
port=5432

[mail]
; See config file documentation for more options
from=tickets@heimbrauconvention.de
; This is the default IP address of your docker host in docker's virtual
; network. Make sure postfix listens on this address.
host=172.17.0.1

[redis]
location=redis://redis/0
; Remove the following line if you are unsure about your redis' security
; to reduce impact if redis gets compromised.
sessions=true

[celery]
backend=redis+socket:redis://redis/1
broker=redis+socket:redis://redis/2
```

pretix.log in the data volume has no entries at all (0 bytes) unfortunately, so I don't really know how to debug this further.
Also, within the container, I can't "su" since I don't know pretixuser's password...

Sorry if this is RTFM; I googled a lot and could not find any solution.

**Comment by DottoreTozzi** [comment]
Ok my problems were due to utter stupidity on my part.

Here's my working configuration for the current pretix container, running behind Træfik as reverse proxy:

docker-compose.yml:
```
version: "3.7"
services:
  dbpretix:
    container_name: dbpretix
    image: postgres:10
    environment:
      POSTGRES_DB: pretix
      POSTGRES_USER: pretix
      POSTGRES_PASSWORD: pretix
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    volumes:
      - pretix-dbdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host

  pretix:
    image: pretix/standalone:stable
    container_name: pretix
    hostname: tickets
    domainname: mydomain.de
    depends_on:
      - redis
      - dbpretix
    volumes:
      - ${DOCKERDIR}/pretix/config/pretix.cfg:/etc/pretix/pretix.cfg
      - pretix-data:/data
    networks:
      - default
      - traefik_proxy
    labels:
      - "traefik.domain=mydomain.de"
      - "traefik.frontend.rule=Host:tickets.mydomain.de"
      - "traefik.enable=true"
      - "traefik.backend=pretix"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=mydomain.de"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=false"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

volumes:
  pretix-data:
    driver: local
  pretix-dbdata:
    driver: local
```

pretix.cfg:
```
[pretix]
instance_name=My Ticketshop
url=https://tickets.mydomain.de
currency=EUR
; DO NOT change the following value, it has to be set to the location of the
; directory *inside* the docker container
datadir=/data

[database]
; Replace postgresql with mysql for MySQL
backend=postgresql
name=pretix
user=pretix
; Replace with the password you chose above
password=xxxxxxx
; In most docker setups, 172.17.0.1 is the address of the docker host. Adjuts
; this to wherever your database is running, e.g. the name of a linked container
; or of a mounted MySQL socket.
host=172.17.0.1
port=5432

[mail]
; See config file documentation for more options
from=tickets@heimbrauconvention.de
; This is the default IP address of your docker host in docker's virtual
; network. Make sure postfix listens on this address.
host=172.17.0.1

[redis]
location=redis://172.17.0.1:6379/0
sessions=true

[celery]
backend=redis://172.17.0.1:6379/1
broker=redis://172.17.0.1:6379/2
```
